name: Lint CSS
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: "Restore cache of JavaScript dependencies"
        uses: actions/cache@v2
        with:
          path: |
            .npm
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Install JavaScript dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --cache .npm
      - name: Run stylelint
        run: node_modules/.bin/stylelint src/**/*.css
